### ISSUE TITLE
Example1 and Example2 doesn't WORK 

### ISSUE THREAD

**Issue by thomasX** [rockfireredmoon/getdown-maven-plugin#6]
we tried to build both examples but it doesn't work ! 
raw.github is no longer supported !
so the project can't build  !
in a secod run we tired to update the plugin, add  a gh-pages repository and build it. 
but when we try to build the examples we always get the error: 
 
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates (default) on project getdown-maven-example2: Execution default of goal org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates failed: Unable to load the mojo 'updates' (or one of its required components) from the plugin 'org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) No implementation for org.icestuff.getdown.maven.SignTool was bound.
[ERROR] while locating org.icestuff.getdown.maven.MakeUpdatesMojo
[ERROR] at ClassRealm[plugin>org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@33909752]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates (default) on project getdown-maven-example2: Execution default of goal org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates failed: Unable to load the mojo 'updates' (or one of its required components) from the plugin 'org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates failed: Unable to load the mojo 'updates' (or one of its required components) from the plugin 'org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'updates' (or one of its required components) from the plugin 'org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:488)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	... 20 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.icestuff.getdown.maven.SignTool was bound.
  while locating org.icestuff.getdown.maven.MakeUpdatesMojo
  at ClassRealm[plugin>org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@33909752]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates)

1 error
      role: org.apache.maven.plugin.Mojo
  roleHint: org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:257)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	... 21 more
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.icestuff.getdown.maven.SignTool was bound.
  while locating org.icestuff.getdown.maven.MakeUpdatesMojo
  at ClassRealm[plugin>org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@33909752]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.icestuff:getdown-maven-plugin:0.0.10-SNAPSHOT:updates)

1 error
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	... 23 more

**Comment by rockfireredmoon** [comment]
Did you ever get to the bottom of this? I can't reproduce this, but it looks for some reason like the signing tool is not being setup correctly. This is a maven @Component, so I thought this should all happen automatically. Maybe it's the Maven version in use.

Anyway .. really, the Signing tools are about obsolete. It is only there to support applets, which are so hard to get running now for the average user it seems pointless to continue supporting them at all. It is suprising Getdown itself does!

**Comment by rockfireredmoon** [comment]
Please re-open if the Maven central release 0.9.0 doesn't work.
